### ISSUE TITLE
Поставил галочку включить логирование

### ISSUE THREAD

**Issue by Gabi1981** [Akurganow/WooCommerce-Robokassa#20]
Помогите плиз. Поставил галочку включить логирование, теперь не могу зайти в настройки вукомерс. Что делать?

**Comment by saphali** [comment]
Обновить до последней версии. Версия плагина должна быть больше 1.0.0

**Comment by AlexMcowkin** [comment]
та же проблема
мы используем wordpress 4.9.2 и woocommerce 3.2.4 
при включении логирования корзина падает и настройки woocommerce тоже.

проблема в том, что на robokassa в отчетах логирования постоянно ошибка IPN Request Failure
уже интересно было узнать что это такое и почему так происходит

**Comment by saphali** [comment]
Здравствуйте. В коде, относительно логирования, ошибок не наблюдается. Нужно видеть саму ошибку при падении. Ее можно увидеть, если включить вывод ошибок на экран в РНР.
Ошибка IPN Request Failure указывает на то, что при проверке подписи она просто не проходит. Предположительно **`Пароль #2`** указан неверно (на стороне Робокассы и в настройках шлюза нет совпадения).

**Comment by AlexMcowkin** [comment]
пасиб. ща буду проверять

**Comment by alex-revo** [comment]
При включении логирования сайт упал с ошибкой
Fatal error: Uncaught Error: Call to undefined method WooCommerce::logger() in /var/www/u0515761/data/www/intelfood.ru/wp-content/plugins/robokassa-for-woocommerce/wc-robokassa.php:73 Stack trace: #0 /var/www/u0515761/data/www/intelfood.ru/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(108): WC_ROBOKASSA->__construct() #1 /var/www/u0515761/data/www/intelfood.ru/wp-content/plugins/woocommerce/includes/admin/settings/class-wc-settings-payment-gateways.php(224): WC_Payment_Gateways->init() #2 /var/www/u0515761/data/www/intelfood.ru/wp-includes/class-wp-hook.php(286): WC_Settings_Payment_Gateways->save('') #3 /var/www/u0515761/data/www/intelfood.ru/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #4 /var/www/u0515761/data/www/intelfood.ru/wp-includes/plugin.php(465): WP_Hook->do_action(Array) #5 /var/www/u0515761/data/www/intelfood.ru/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-settings.php(75): do_action('woocommerce_set...') #6 /var/www/u0515761/data/www/intelfood in /var/www/u0515761/data/www/intelfood.ru/wp-content/plugins/robokassa-for-woocommerce/wc-robokassa.php on line 73

**Comment by saphali** [comment]
В стр 73 нет вызова WooCommerce::logger. Если не последняя версия плагина, то обновитесь.

**Comment by saphali** [comment]
> В стр 73 нет вызова WooCommerce::logger. Если непоследняя версия плагина, то обновитесь.
